version: '3'

services:
  algod:
    container_name: voi-testnet
    image: scholtz2/algorand-participation-voitest-extended:3.19.0-stable
    ports:
      - 4190:28081
    environment:
      - NETWORK=voitest
      - FAST_CATCHUP=1
      - PROFILE=participation
    volumes:
      - ${PWD}/data:/app/data/:rw
      - ${PWD}/config.json:/etc/algorand/config.json:rw
    networks:
      - app-net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - app-net
    depends_on:
      - algod
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-net
    depends_on:
      - prometheus
networks:
  host:
    external: true
  app-net:
    driver: bridge
