version: '3'

services:
  algod:
    container_name: blockchain-node
    image: algorand/algod:beta
    ports:
      - 4190:8080
    environment:
      - NETWORK=betanet
      - FAST_CATCHUP=1
      - PROFILE=participation
    volumes:
      - ${PWD}/data:/algod/data/:rw
      - ${PWD}/config.json:/etc/algorand/config.json:rw
networks:
  host:
    external: true
