version: '3'

services:
  algod:
    container_name: voi-testnet
    image: ghcr.io/voinetwork/docker-participation-node:latest
    ports:
      - 4190:8080
    env_file:
      - docker.env
    environment:
      - NETWORK=voitest
    volumes:
      - ${PWD}/data:/algod/data/:rw
    networks:
      - app-net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - app-net
    depends_on:
      - algod
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-net
    depends_on:
      - prometheus
networks:
  host:
    external: true
  app-net:
    driver: bridge
