version: '3'

services:
  algod:
    container_name: algorand-betanet
    image: algorand/algod:latest
    ports:
      - 4190:8080
    environment:
      - NETWORK=betanet
      - FAST_CATCHUP=1
      - PROFILE=participation
    volumes:
      - ${PWD}/data:/algod/data/:rw
      - ${PWD}/config.json:/etc/algorand/config.json:rw
    networks:
      - app-net
networks:
  host:
    external: true
  app-net:
    driver: bridge

