name: Update installer

on:
  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download pixelnode agent
        run: |
            wget -O pixelnode.zip https://pixelnode.nyc3.digitaloceanspaces.com/builds/prod.zip

      - name: Unzip pixelnode agent
        run: |
          rm -rf pixelnode
          unzip pixelnode.zip
          rm -rf pixelnode.zip
          mv ./pixelnode/docker-compose.algorand.mainnet.yml docker-compose.algorand.mainnet.yml
          mv ./pixelnode/docker-compose.algorand.testnet.yml docker-compose.algorand.testnet.yml
          mv ./pixelnode/docker-compose.algorand.betanet.yml docker-compose.algorand.betanet.yml
          mv ./pixelnode/docker-compose.voi.testnet.yml docker-compose.voi.testnet.yml
          rm -rf ./prometheus
          mv ./pixelnode/prometheus .
          mv ./pixelnode/package.json package.json
          mv ./pixelnode/yarn.lock yarn.lock

      - name: Commit and push changes
        run: |
          git config user.name "shivamanupadi"
          git config user.email "shivaprasadmanupadi@gmail.com"
          git add .
          git commit -m "Update installer"
          git push origin HEAD:master

